upstream wordpress {
    server 127.0.0.1:8000
}

upstream phpmyadmin {
    server 127.0.0.1:8080;
}

server {
    listen 80;
    server_name store.trondealer.com;

    client_max_body_size 64m;
    access_log /var/log/nginx/db-access.log;
    error_log /var/log/nginx/db-error.log;

    location / {
        proxy_pass http://wordpress;
        proxy_pass_header       Set-Cookie;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /phpmyadmin/ {
        proxy_pass http://phpmyadmin/;
        proxy_pass_header       Set-Cookie;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    if ($request_method !~ ^(GET|HEAD|POST|PUT|DELETE|OPTIONS)$ ) {
        return 405;
    }

    location = /wp-login.php {
        limit_req zone=login burst=3 nodelay;
        include fastcgi_params;
        fastcgi_pass wordpress_php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /wp-admin/ {
        limit_req zone=login burst=5 nodelay;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~* /wp-json/ {
        limit_req zone=api burst=30;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ /\.ht {
        deny all;
    }

    location = /xmlrpc.php {
        deny all;
        return 403;
    }


    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform, immutable";
        access_log off;
        log_not_found off;
        try_files $uri $uri/ =404;
    }

}
