upstream wp {
    server 127.0.0.1:8000;
}

upstream pma {
    server 127.0.0.1:8080;
}

server {
    listen 80;
    server_name store.trondealer.com;

    client_max_body_size 64m;
    access_log /var/log/nginx/store-trondealer-access.log;
    error_log /var/log/nginx/store-trondealer-error.log;

    location / {
        proxy_pass http://wp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /phpmyadmin/ {
        proxy_pass http://pma/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Ssl on;
    }

location /wp-admin/ {
        proxy_pass http://wp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location = /wp-login.php {
	    limit_req zone=login burst=3 nodelay;
	    proxy_pass http://wp;
	    proxy_set_header Host $host;
	    proxy_set_header X-Forwarded-Proto https;
    }

    location ~* /wp-json/ {
        limit_req zone=api burst=30;
        proxy_pass http://wp;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location ~* /(wp-config\.php|wp-config-sample\.php|readme\.html|license\.txt|\.git|\.env|\.htaccess|\.htpasswd|\.user\.ini|php\.ini|php\.log|error_log) {
        deny all;
        access_log off;
        log_not_found off;
        return 403;
    }

    location ~ /\.ht {
        deny all;
        access_log off;
        log_not_found off;
    }

    location = /xmlrpc.php {
        deny all;
        access_log off;
        log_not_found off;
        return 403;
    }

    location ~* /wp-content/uploads/wc-logs/ {
        deny all;
        return 403;
    }

    location ~* /wp-content/plugins/woocommerce/templates/ {
        deny all;
        return 403;
    }

    if ($block_bad_bots) {
        return 403;
    }

    add_header Access-Control-Allow-Origin https://store.trondealer.com always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;
    add_header Access-Control-Allow-Credentials "true" always;

    proxy_cookie_flags ~ Secure HttpOnly SameSite=Lax;

    add_header X-Powered-By "";

    add_header Expect-CT "max-age=86400, enforce" always;
    add_header X-Permitted-Cross-Domain-Policies none always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), fullscreen=(), payment=()" always;

    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;

add_header Content-Security-Policy "default-src https:; script-src 'unsafe-inline' 'self' https://kit.fontawesome.com/ blob:; style-src 'unsafe-inline' 'self'; font-src 'self' data:; img-src 'self' https://secure.gravatar.com/avatar/ data:; connect-src https://kit.fontawesome.com/; frame-src blob:; frame-ancestors 'self'; object-src 'none'; base-uri 'self';";
}
